# 06_export_hd_features_table.R
# Generate a LaTeX table summarising the HD features used by hdiCF.
#
# Reads:  data/hd_features.rds
# Writes: output/hd_features_table.tex

suppressPackageStartupMessages({
  library(dplyr)
  library(here)
})
here::i_am("suicidality/analysis-hdicf/06_export_hd_features_table.R")

hd <- readRDS(here("suicidality", "analysis-hdicf", "data", "hd_features.rds"))
N <- nrow(hd)

# ICD-10 3-character labels for codes that appear as HD features.
icd_labels <- c(
  F00 = "Dementia in Alzheimer's disease",
  F10 = "Alcohol use disorder",
  F12 = "Cannabinoid use disorder",
  F19 = "Multiple substance use disorder",
  F31 = "Bipolar affective disorder",
  F32 = "Depressive episode",
  F33 = "Recurrent depressive disorder",
  F40 = "Phobic anxiety disorder",
  F41 = "Other anxiety disorder",
  F42 = "Obsessive--compulsive disorder",
  F43 = "Reaction to severe stress / adjustment disorder",
  F50 = "Eating disorder",
  F51 = "Non-organic sleep disorder",
  F60 = "Specific personality disorder",
  F70 = "Mild intellectual disability",
  F84 = "Autism spectrum disorder",
  F90 = "Hyperkinetic disorder (ADHD)",
  F91 = "Conduct disorder",
  F98 = "Other behavioural / emotional disorder of childhood",
  T50 = "Poisoning by drugs and biological substances",
  X64 = "Intentional self-poisoning by drugs (NOS)",
  X78 = "Intentional self-harm by sharp object"
)

# ATC 4-character labels for prescription HD features.
atc_labels <- c(
  N03AX = "Other antiepileptics",
  N05AH = "Atypical antipsychotics (diazepines / thiazepines)",
  N05AX = "Other antipsychotics",
  N05B  = "Anxiolytics",
  N05BA = "Benzodiazepine anxiolytics",
  N05C  = "Hypnotics and sedatives",
  N05CF = "Benzodiazepine-related hypnotics (Z-drugs)",
  N05CH = "Melatonin receptor agonists",
  N06BA = "Centrally acting sympathomimetics (ADHD stimulants)"
)

cols <- setdiff(names(hd), "lopnr")
prev_pct <- vapply(cols, function(c) 100 * mean(hd[[c]] > 0), numeric(1))

rows <- data.frame(
  feature = cols,
  prev_pct = prev_pct,
  stringsAsFactors = FALSE
) %>%
  mutate(
    prefix = case_when(
      startsWith(feature, "dx.inp.") ~ "dx.inp",
      startsWith(feature, "dx.out.") ~ "dx.out",
      startsWith(feature, "rx.")     ~ "rx",
      TRUE                            ~ NA_character_
    ),
    code = case_when(
      prefix == "dx.inp" ~ sub("^dx\\.inp\\.", "", feature),
      prefix == "dx.out" ~ sub("^dx\\.out\\.", "", feature),
      prefix == "rx"     ~ sub("^rx\\.",       "", feature),
      TRUE                ~ feature
    ),
    section = case_when(
      prefix == "dx.inp" ~ "Inpatient ICD-10",
      prefix == "dx.out" ~ "Outpatient ICD-10",
      prefix == "rx"     ~ "ATC (90 days before baseline)",
      TRUE               ~ prefix
    ),
    label = case_when(
      prefix %in% c("dx.inp", "dx.out") ~ icd_labels[code],
      prefix == "rx"                    ~ atc_labels[code],
      TRUE                               ~ NA_character_
    )
  ) %>%
  arrange(section, desc(prev_pct))

# Build LaTeX output
section_order <- c("Inpatient ICD-10", "Outpatient ICD-10", "ATC (90 days before baseline)")
lines <- c()
for (sec in section_order) {
  sub <- rows %>% filter(section == sec)
  if (nrow(sub) == 0) next
  lines <- c(lines, sprintf("\\textit{%s} & & \\\\", sec))
  for (i in seq_len(nrow(sub))) {
    label <- if (is.na(sub$label[i])) "(no label)" else sub$label[i]
    lines <- c(lines, sprintf("\\quad \\texttt{%s} & %s & %.2f \\\\",
                              sub$feature[i], label, sub$prev_pct[i]))
  }
  lines <- c(lines, "\\addlinespace")
}

# Trim final addlinespace
if (length(lines) > 0 && grepl("addlinespace", tail(lines, 1))) {
  lines <- head(lines, -1)
}

out_dir <- here("suicidality", "analysis-hdicf", "output")
out_path <- file.path(out_dir, "hd_features_table.tex")
writeLines(c("% Auto-generated by 06_export_hd_features_table.R -- do not edit manually",
             lines), out_path)
cat(sprintf("Saved: %s (%d HD features, N = %d)\n", out_path, length(cols), N))
