# 04_export_missind_triage.R
# Emit LaTeX macros summarising the missing-indicator step-1 triage rerun of
# the iCF and hdiCF pipelines (see tools/submit_{icf,hdicf}_step1_missind.sh).
#
# Reads:
#   analysis-icf/output/icf_step1_missind.rds
#   analysis-hdicf/output/icf_step1_missind.rds
# Writes:
#   analysis-icf/output/missind_triage_values.tex   (\missindICF*, \missindHdicf*)

library(here)
here::i_am("suicidality/analysis-icf/04_export_missind_triage.R")

icf  <- readRDS(here("suicidality", "analysis-icf",   "output", "icf_step1_missind.rds"))
hdcf <- readRDS(here("suicidality", "analysis-hdicf", "output", "icf_step1_missind.rds"))

format_n <- function(n) format(n, big.mark = "{,}", scientific = FALSE)
format_p <- function(p) {
  if (p < 1e-3) sprintf("%.2g", p) else sprintf("%.3f", p)
}

# Build a sorted VI data frame for one step1 bundle and look up any_miss.
vi_lookup <- function(step1) {
  df <- data.frame(variable = step1$var_names,
                   importance = as.numeric(step1$var_imp))
  df <- df[order(-df$importance), , drop = FALSE]
  rownames(df) <- NULL
  am <- df[df$variable == "any_miss", , drop = FALSE]
  list(
    df         = df,
    mean_vi    = mean(df$importance),
    n_total    = nrow(df),
    any_miss_vi = am$importance,
    any_miss_rank = which(df$variable == "any_miss")
  )
}

emit <- function(prefix, step1, label) {
  vi <- vi_lookup(step1)
  jacc <- step1$vi_stability$mean_offdiag_jaccard
  c(
    sprintf("%% --- %s (missing-indicator step-1 triage) ---", label),
    sprintf("\\newcommand{\\%sCohortN}{%s}",        prefix, format_n(nrow(step1$X))),
    sprintf("\\newcommand{\\%sHetP}{%s}",           prefix, format_p(step1$het_p)),
    sprintf("\\newcommand{\\%sNSelected}{%d}",      prefix, length(step1$selected_vars)),
    sprintf("\\newcommand{\\%sNCandidates}{%d}",    prefix, vi$n_total),
    sprintf("\\newcommand{\\%sMeanVI}{%.4f}",       prefix, vi$mean_vi),
    sprintf("\\newcommand{\\%sViStabJaccard}{%.2f}", prefix, jacc),
    sprintf("\\newcommand{\\%sAnyMissVI}{%.4f}",    prefix, vi$any_miss_vi),
    sprintf("\\newcommand{\\%sAnyMissRank}{%d}",    prefix, vi$any_miss_rank)
  )
}

lines <- c(
  "% Auto-generated by analysis-icf/04_export_missind_triage.R -- do not edit manually",
  sprintf("%% Generated: %s", Sys.time()),
  "",
  emit("missindICF",   icf,  "iCF"),
  "",
  emit("missindHdicf", hdcf, "hdiCF")
)

out <- here("suicidality", "analysis-icf", "output", "missind_triage_values.tex")
writeLines(lines, out)
cat("Saved:", out, "\n")

# Also drop a copy into the 2026-05-22 snapshot so the Makefile (which points
# ICF_DIR at the snapshot) picks it up without further reconfiguration.
snap <- here("suicidality", "analysis-icf", "gitignore",
             "output-backup-2026-05-22", "missind_triage_values.tex")
if (dir.exists(dirname(snap))) {
  file.copy(out, snap, overwrite = TRUE)
  cat("Mirrored to snapshot:", snap, "\n")
}
