# export_thesis_values.R
# Generate LaTeX macros for all thesis values from study data
#
# Reads the main analysis dataset, computes ITT estimates, and exports all
# numeric values used in thesis.tex as \newcommand definitions.
#
# Output: suicidality/report/generated/thesis_values.tex
#
# Usage: Rscript suicidality/analysis/export_thesis_values.R

library(survival)
library(dplyr)
library(here)
here::i_am("suicidality/analysis/export_thesis_values.R")

source(here("suicidality", "analysis", "common.R"))

# =============================================================================
# HELPERS
# =============================================================================

lines <- character()
cmd <- function(name, value) {
  lines <<- c(lines, sprintf("\\newcommand{\\%s}{%s}", name, value))
}
comment <- function(text) {
  lines <<- c(lines, paste0("% ", text))
}

format_n <- function(n) {
  format(n, big.mark = "{,}", scientific = FALSE)
}

format_pct <- function(x, digits = 1) {
  sprintf(paste0("%.", digits, "f"), x)
}

format_rd <- function(x, digits = 2) {
  sprintf(paste0("%.", digits, "f"), x)
}

# Signed RD format for point estimates: prepends "+" for positive values so
# directionality is unambiguous in tables (matches the convention used in
# cate_by_source.R and the iCF/hdiCF export scripts). CI bounds and risks
# stay unsigned via format_rd().
format_rd_signed <- function(x, digits = 2) {
  s <- sprintf(paste0("%.", digits, "f"), x)
  if (!is.na(x) && x >= 0) paste0("+", s) else s
}

format_rr <- function(x, digits = 2) {
  sprintf(paste0("%.", digits, "f"), x)
}

# =============================================================================
# LOAD DATA
# =============================================================================

cat("Loading main analysis data...\n")
full_data_raw <- read_rds_file("main_12wks_28.rds")
full_data <- filter_complete_cases(full_data_raw)
n_excluded_cca <- nrow(full_data_raw) - nrow(full_data)
pct_excluded_cca <- 100 * n_excluded_cca / nrow(full_data_raw)

# =============================================================================
# STUDY POPULATION
# =============================================================================

comment("Auto-generated by export_thesis_values.R -- do not edit manually")
comment(paste("Generated:", Sys.time()))
comment("")

comment("=== Study Population ===")
n_total <- nrow(full_data)
n_initiators <- sum(full_data$cc == 1)
n_noninitiators <- sum(full_data$cc == 0)
pct_initiators <- 100 * n_initiators / n_total

cmd("studyN", format_n(n_total))
cmd("studyNEligible", format_n(nrow(full_data_raw)))   # pre-CCA cohort
cmd("studyNInitiators", format_n(n_initiators))
cmd("studyNNoninitiators", format_n(n_noninitiators))
# Pre-CCA initiator/non-initiator counts (Table 2 describes the eligible cohort)
cmd("studyNEligibleInitiators",
    format_n(sum(full_data_raw$cc == 1, na.rm = TRUE)))
cmd("studyNEligibleNoninitiators",
    format_n(sum(full_data_raw$cc == 0, na.rm = TRUE)))
cmd("studyPctInitiators", format_pct(pct_initiators))
cmd("studyPctNoninitiators", format_pct(100 - pct_initiators))
cmd("cohortExcludedCCA", format_n(n_excluded_cca))
cmd("cohortExcludedCCAPct", format_pct(pct_excluded_cca, digits = 2))

# Initiators with predi_diff in (14, 28] are reclassified as non-initiators
# under the 14-day grace-period sensitivity. Two scopes: pre-CCA cohort
# (the cohort-rebuild reclassification), and the analysis cohort (CCA).
n_reclass_rebuild  <- sum(full_data_raw$cc == 1 & full_data_raw$predi_diff > 14, na.rm = TRUE)
n_reclass_analysis <- sum(full_data$cc == 1     & full_data$predi_diff > 14,     na.rm = TRUE)
cmd("cohortReclassFourteenRebuild",  format_n(n_reclass_rebuild))
cmd("cohortReclassFourteenAnalysis", format_n(n_reclass_analysis))
lines <- c(lines, "")

comment("=== Demographics ===")
pct_female <- 100 * mean(full_data$female == 1)
mean_age <- mean(full_data$age)
sd_age <- sd(full_data$age)

cmd("studyPctFemale", format_pct(pct_female))
cmd("studyMeanAge", format_pct(mean_age, 0))
cmd("studySdAge", format_pct(sd_age))
lines <- c(lines, "")

comment("=== Events ===")
events_total <- sum(full_data$sb12_itt == 1)
events_initiators <- sum(full_data$cc == 1 & full_data$sb12_itt == 1)
events_noninitiators <- sum(full_data$cc == 0 & full_data$sb12_itt == 1)
event_rate <- 100 * events_total / n_total

cmd("studyEvents", format_n(events_total))
cmd("studyEventsInitiators", format_n(events_initiators))
cmd("studyEventsNoninitiators", format_n(events_noninitiators))
cmd("studyEventRate", format_pct(event_rate))
lines <- c(lines, "")

# =============================================================================
# ITT ANALYSIS (replicating core of ITT_12wks.R)
# =============================================================================

cat("Running ITT analysis...\n")

run_itt <- function(data, include_female = TRUE) {
  data$t_end <- ceiling((data$fu_end_itt - data$fu_start) / 7)
  data$diag_anxiety <- as.integer(data$diag_phobic == 1 | data$diag_anxiety_other == 1)

  # Propensity score model
  demo_vars <- if (include_female) "female + age + year" else "age + year"
  socio_vars <- paste(
    "relevel(as.factor(edufam_cat), ref='1')",
    "relevel(as.factor(source), ref='O')",
    "relevel(as.factor(inc_cat), ref='2')",
    sep = " + "
  )
  fh_vars <- paste(
    "relevel(as.factor(fh_suicidal), ref='0')",
    "relevel(as.factor(fh_depr), ref='0')",
    sep = " + "
  )
  diag_vars <- paste(
    "diag_mdd", "diag_bipolar", "diag_psychotic", "diag_alcohol", "diag_sud",
    "diag_autism", "diag_adhd", "diag_suicidal", "diag_overdose",
    "diag_stress", "diag_anxiety",
    "diag_sleep", "diag_anorexia", "diag_bulimia",
    "diag_ocd", "diag_conduct", "diag_intellectual_disability", "diag_personality_cluster_b",
    sep = " + "
  )
  med_vars <- paste(
    "med_antipsychotic", "med_hypnotic", "med_benzodiazepine", "med_antiepileptic",
    "med_stimulant", "med_opioid", "med_mood_stabilizer", "med_addiction",
    sep = " + "
  )
  formula_str <- paste("cc ~", demo_vars, "+", socio_vars, "+", fh_vars, "+",
                       "hosp +", diag_vars, "+", med_vars)
  ps_formula <- as.formula(formula_str)

  p.denom <- glm(ps_formula, data = data, family = binomial())
  data$pd.cc <- predict(p.denom, type = "response")
  p.num <- glm(cc ~ 1, data = data, family = binomial())
  data$pn.cc <- predict(p.num, type = "response")

  data$sw.a <- ifelse(data$cc == 1,
                      data$pn.cc / data$pd.cc,
                      (1 - data$pn.cc) / (1 - data$pd.cc))
  q99 <- quantile(data$sw.a, 0.99, na.rm = TRUE)
  data$sw.a <- pmin(data$sw.a, q99)

  km_fit <- survfit(Surv(t_end, sb12_itt) ~ cc, weights = sw.a, cluster = lopnr, data = data)
  surv_12 <- summary(km_fit, times = 12)

  control_idx <- which(surv_12$strata == "cc=0")
  treated_idx <- which(surv_12$strata == "cc=1")

  risk_control <- (1 - surv_12$surv[control_idx]) * 100
  risk_treated <- (1 - surv_12$surv[treated_idx]) * 100
  se_control <- surv_12$std.err[control_idx] * 100
  se_treated <- surv_12$std.err[treated_idx] * 100

  rd <- risk_treated - risk_control
  rd_se <- sqrt(se_control^2 + se_treated^2)
  rd_lower <- rd - 1.96 * rd_se
  rd_upper <- rd + 1.96 * rd_se

  rr <- risk_treated / risk_control
  log_rr_se <- sqrt((se_treated / risk_treated)^2 + (se_control / risk_control)^2)
  rr_lower <- exp(log(rr) - 1.96 * log_rr_se)
  rr_upper <- exp(log(rr) + 1.96 * log_rr_se)

  list(
    risk_control = risk_control, risk_treated = risk_treated,
    rd = rd, rd_lower = rd_lower, rd_upper = rd_upper,
    rr = rr, rr_lower = rr_lower, rr_upper = rr_upper
  )
}

# Full cohort ITT
itt_main <- run_itt(full_data)

comment("=== ITT Results (Full Cohort, 12 weeks) ===")
cmd("ittRiskControl", format_rd(itt_main$risk_control))
cmd("ittRiskTreated", format_rd(itt_main$risk_treated))
cmd("ittRD", format_rd_signed(itt_main$rd))
cmd("ittRDLower", format_rd(itt_main$rd_lower))
cmd("ittRDUpper", format_rd(itt_main$rd_upper))
cmd("ittRR", format_rr(itt_main$rr))
cmd("ittRRLower", format_rr(itt_main$rr_lower))
cmd("ittRRUpper", format_rr(itt_main$rr_upper))
lines <- c(lines, "")

cat("  ITT RD:", round(itt_main$rd, 3), "RR:", round(itt_main$rr, 3), "\n")

# Age-stratified ITT
itt_6_17 <- run_itt(full_data[full_data$age >= 6 & full_data$age <= 17, ])
itt_18_24 <- run_itt(full_data[full_data$age >= 18 & full_data$age <= 24, ])

comment("=== ITT Results (Age 6-17) ===")
cmd("ittYoungRD", format_rd_signed(itt_6_17$rd))
cmd("ittYoungRDLower", format_rd(itt_6_17$rd_lower))
cmd("ittYoungRDUpper", format_rd(itt_6_17$rd_upper))
cmd("ittYoungRR", format_rr(itt_6_17$rr))
cmd("ittYoungRRLower", format_rr(itt_6_17$rr_lower))
cmd("ittYoungRRUpper", format_rr(itt_6_17$rr_upper))
lines <- c(lines, "")

comment("=== ITT Results (Age 18-24) ===")
cmd("ittAdultRD", format_rd_signed(itt_18_24$rd))
cmd("ittAdultRDLower", format_rd(itt_18_24$rd_lower))
cmd("ittAdultRDUpper", format_rd(itt_18_24$rd_upper))
cmd("ittAdultRR", format_rr(itt_18_24$rr))
cmd("ittAdultRRLower", format_rr(itt_18_24$rr_lower))
cmd("ittAdultRRUpper", format_rr(itt_18_24$rr_upper))
lines <- c(lines, "")

# Sex-stratified ITT
itt_female <- run_itt(full_data[full_data$female == 1, ], include_female = FALSE)
itt_male <- run_itt(full_data[full_data$female == 0, ], include_female = FALSE)

comment("=== ITT Results (Female) ===")
cmd("ittFemaleRD", format_rd_signed(itt_female$rd))
cmd("ittFemaleRDLower", format_rd(itt_female$rd_lower))
cmd("ittFemaleRDUpper", format_rd(itt_female$rd_upper))
cmd("ittFemaleRR", format_rr(itt_female$rr))
cmd("ittFemaleRRLower", format_rr(itt_female$rr_lower))
cmd("ittFemaleRRUpper", format_rr(itt_female$rr_upper))
lines <- c(lines, "")

comment("=== ITT Results (Male) ===")
cmd("ittMaleRD", format_rd_signed(itt_male$rd))
cmd("ittMaleRDLower", format_rd(itt_male$rd_lower))
cmd("ittMaleRDUpper", format_rd(itt_male$rd_upper))
cmd("ittMaleRR", format_rr(itt_male$rr))
cmd("ittMaleRRLower", format_rr(itt_male$rr_lower))
cmd("ittMaleRRUpper", format_rr(itt_male$rr_upper))
lines <- c(lines, "")

# =============================================================================
# STUDY PERIOD
# =============================================================================

comment("=== Study Period ===")
cmd("studyStartDate", "1 July 2006")
cmd("studyEndDate", "31 December 2019")
cmd("studyEndFollowup", "31 December 2020")
lines <- c(lines, "")

# =============================================================================
# WRITE OUTPUT
# =============================================================================

output_dir <- here("suicidality", "analysis-icf", "output")
output_path <- file.path(output_dir, "thesis_values.tex")
writeLines(lines, output_path)
cat("Saved:", output_path, "\n")

cat("\n=== Thesis Values Export Complete ===\n")
cat("Values generated:", length(grep("^\\\\newcommand", lines)), "\n")
